#!/usr/bin/env python3
"""Generate a self-contained C header by recursively expanding local includes."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

INCLUDE_RE = re.compile(r"^(?P<indent>\s*)#\s*include\s*[<\"](?P<name>[^>\"]+)[>\"]\s*$")
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--include-dir", action="append", type=Path, default=[])
    return parser.parse_args()


def resolve_local(name: str, current: Path, include_dirs: list[Path]) -> Path | None:
    candidates = [current.parent / name]
    candidates.extend(directory / name for directory in include_dirs)
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    return None


def expand(path: Path, include_dirs: list[Path], emitted: set[Path], output: list[str]) -> None:
    path = path.resolve()
    if path in emitted:
        return
    emitted.add(path)
    output.append(f"/* --- begin {path.name} --- */\n")
    for line in path.read_text(encoding="utf-8").splitlines(keepends=True):
        match = INCLUDE_RE.match(line.rstrip("\n"))
        if match is None:
            output.append(line)
            continue
        dependency = resolve_local(match.group("name"), path, include_dirs)
        if dependency is None:
            if line.lstrip().startswith("#include <"):
                output.append(line)
            else:
                raise RuntimeError(
                    f"unresolved local include {match.group('name')!r} in {path}"
                )
            continue
        expand(dependency, include_dirs, emitted, output)
    output.append(f"/* --- end {path.name} --- */\n")


def main() -> int:
    args = parse_args()
    header = args.header.resolve()
    include_dirs = [directory.resolve() for directory in args.include_dir]
    body: list[str] = []
    expand(header, include_dirs, set(), body)
    guard = re.sub(r"[^A-Za-z0-9]", "_", args.output.stem.upper()) + "_SINGLE_H"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "/* Generated by tools/amalgamate_headers.py; do not edit manually. */\n"
        f"#ifndef {guard}\n#define {guard}\n\n"
        + "".join(body)
        + f"\n#endif /* {guard} */\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
